---
title: ""
output: pdf_document
params:
  filename: "test filename"
  date: "test date"
  tidy_data: NA
  git_tag: NA
  git_id_short: NA
header-includes:
  - \usepackage{lastpage}
  - \usepackage{fancyhdr}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \pagestyle{fancy}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(knitr)
library(kableExtra)

```

```{r prepare_filename}
# replace _ of filename with \_ to prevent latex from entering the math mode
# see https://xkcd.com/1638/ and https://github.com/STAT545-UBC/Discussion/issues/394
# CAUTION some symbols (e.g "--") might still be formatted differently
filename_header <- paste(str_replace_all(params$filename, "_", "\\\\_"), "-", params$date)
```

\fancyhead[CO,C]{`r filename_header`}
\cfoot{\thepage\ of \pageref{LastPage}}

Report Creation Time: `r format(Sys.time(), usetz = TRUE)`  
Utility2MOLIS Version: `r params$git_tag` (`r params$git_id_short`)

```{r table}
# leaves cells with NA blank instead of printing NA
options(knitr.kable.NA = "")

tidy_data <- params$tidy_data

pos_res <- which(tidy_data$Result == "Positiv")

# create a custom vector which will be used to include a linesep after each Result change
linesep_custom <-
  tidy_data %>%
  mutate(not_same = if_else(Result == lead(Result), "", "\\addlinespace"),
         not_same = replace_na(not_same, "")) %>%
  pull(not_same)

tidy_data %>%
  kable(format = "latex", longtable = TRUE, booktabs = TRUE, linesep = linesep_custom) %>%
  kable_styling(latex_options = c("hold_position", "repeat_header")) %>%
  row_spec(pos_res, bold = TRUE)


```
